### PR TITLE
Add a warning to the random beacon contracts API docs

### PR DESCRIPTION
**Pull request by michalinacienciala**
We want to inform readers that the documented contracts have not been deployed on Mainnet yet.

### CODE REVIEW

**Review by erdogan — APPROVED** [review]

**Comment by michalinacienciala** [comment]
>  Did not see the formatted version (not sure how to view it) but saw the text in code and seems like standard info/warning box.

@erdogan, you can see the formatted Markdown in the 'Files changed' tab, by clicking on the 📄 icon in the header bar with the filename. However this will only apply Markdown formatting and will not apply the GitBook's one (the warning box uses a GitBook-specific syntax). I don't think we have a way to see a preview before merging this. But if we merge today and we notice something went wrong, I can revert the changes.

**Comment by erdogan** [comment]
Sounds great @michalinacienciala let's move forward with it!

**Comment by michalinacienciala** [comment]
@jMyles, @erdogan, looks like the warning formatting did work. See for example [here](https://docs.threshold.network/app-development/random-beacon/random-beacon-api/altbn128).

**Comment by erdogan** [comment]
Yes, looks good!

**Pull request merged**
